osc_server:
  address: 224.0.0.1
  port: 8888

admin_server_port: 8000

configuration_database: /home/flashlight/config.db

searchlights:
  - name: "1"
    positioning_mode: direct
    # TODO: Get real position for 1.
    position: [40.79704, -119.19889]
    zero_position: [40.78639, -119.20647]
    target_grid:
      upper_left: [40.80075, -119.21187]
      upper_right: [40.78249, -119.18758]
      lower_left: [40.78990, -119.22544]
    draw_grid:
      azimuth_angle_bound: [-45, 45]
      elevation_angle_bound: [35, 80]
    direct_positioning:
      azimuth_angle_bound: [-90, 90]
      elevation_angle_bound: [0, 90]
    mirror_positioning:
      azimuth_angle_bound: [-90, 90]
      elevation_angle_bound: [0, 90]
      degrees_at_zero_position: 0
    motor_controller:
      num_channels: 2
      serial_port: "/dev/ttyUSB1"
  - name: "2"
    positioning_mode: direct
    # TODO: Get real position for 2.
    position: [40.79704, -119.19889]
    zero_position: [40.78639, -119.20647]
    target_grid:
      upper_left: [40.80075, -119.21187]
      upper_right: [40.78249, -119.18758]
      lower_left: [40.78990, -119.22544]
    draw_grid:
      azimuth_angle_bound: [-45, 45]
      elevation_angle_bound: [35, 80]
    direct_positioning:
      azimuth_angle_bound: [-90, 90]
      elevation_angle_bound: [0, 90]
    mirror_positioning:
      azimuth_angle_bound: [-90, 90]
      elevation_angle_bound: [0, 90]
      degrees_at_zero_position: 0
    motor_controller:
      num_channels: 2
      serial_port: "/dev/ttyUSB0"

psmove_controllers:
  - searchlight_names: ["1"]
  - searchlight_names: ["2"]
