osc_server:
  address: 224.0.0.1
  port: 8888

admin_server_port: 8000

configuration_database: "../database/config.db"

searchlights:
  - name: "1"
    positioning_mode: direct
    motor_controller:
      num_channels: 2
      serial_port: ""

  - name: "2"
    positioning_mode: direct
    motor_controller:
      num_channels: 2
      serial_port: ""
