osc_server:
  address: 224.0.0.1
  port: 8888

admin_server_port: 8000

configuration_database: "/home/flashlight/config.db"

searchlights:
  - name: "1"
    positioning_mode: direct
    draw_grid:
      azimuth_angle_bound: [-45, 45]
      elevation_angle_bound: [35, 80]
    direct_positioning:
      azimuth_angle_bound: [-90, 90]
      elevation_angle_bound: [0, 90]
    motor_controller:
      num_channels: 2
      serial_port: ""

  - name: "2"
    positioning_mode: direct
    draw_grid:
      azimuth_angle_bound: [-45, 45]
      elevation_angle_bound: [35, 80]
    direct_positioning:
      azimuth_angle_bound: [-90, 90]
      elevation_angle_bound: [0, 90]
    motor_controller:
      num_channels: 2
      serial_port: ""

psmove_controllers:
  - searchlight_names: ["1"]
    color_rgb: [255, 243, 0]

  - searchlight_names: ["2"]
    color_rgb: [114, 206, 1]
